### ISSUE TITLE
confd not compiled with latest go

### ISSUE THREAD

**Issue by cpoole** [rawmind0/alpine-conf#1]
Hey @rawmind0,

I was forking your rancher traefik image to add some custom functionality and ran into an issue with some of the newer go templating language abilities (specifically {{- and  -}} to trim whitespace). 

Confd unfortunately seems be very slow to update, the latest 0.12 update was February 24th and there has been little word from kelsey hightower since then. 

How would you feel about basing this image off of the 0.12-alpha3 release of confd (build with go 1.6) or basing this image off the 0.11 commit but building against go 1.6?

I'm happy to help if either of these seem like options you're ok with

**Comment by rawmind0** [comment]
Hi @cpoole,

Which version of the image are you using?? 
Since alpine-tools 0.3.4, confd was already build with go 1.6. You could see it in the image build log, https://hub.docker.com/r/rawmind/alpine-tools/builds/byp4mvw6fpu5uzel3mlmyy7/

It's no problem to update confd to 0.12-alpha3. I just update alpine-tools and rancher-tools images with it. 
alpine-tools:0.3.4-2 and rancher-tools:0.3.4-3

:)

**Comment by cpoole** [comment]
ah perfect! with the update to the dockerfile your alpine-tools:0.3.4-1 image works perfectly with whitespace stripping. Thanks for the quick help!

I made a formatting change to the rules.toml.tmpl file so that it is easier to read (at least I think so) and I added a manual option if a user wants to set their own domain prefix and service name with labels. 

you can check it out here https://github.com/cpoole/rancher-traefik/blob/master/root/opt/tools/confd/etc/templates/rules.toml.tmpl 

I can submit a pull request if you want these features in your image.
